rabbit:
  broadcast: false

server:
  port: ${PORT:8080}
  shutdown: graceful
  servlet:
    context-path: /chat

logging:
  include-application-name: false
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level[net.talaatharb]: DEBUG
  level[org.springframework.web]: DEBUG

spring:
  datasource:
    url: jdbc:h2:file:./db/chat-backend;AUTO_SERVER=TRUE;
    username: sa
    password:
  jackson:
    mapper[DEFAULT_VIEW_INCLUSION]: true
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: update
  application:
    name: chat-backend
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.0}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
